
include:
  - template: Auto-DevOps.gitlab-ci.yml

stages:
  - pytest
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - release-imgages
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

pytest-feature:
  stage: pytest
  image: python:3.8
  script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - echo "Running custom tests"
    - pip install -r requirements.txt
    - pytest  tests/test-app.py
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'  # This runs on branches starting with 'feature/'
      when: always
    - when: never # Aviod running in other branches

pysec-tests:
  stage: test
  image: python:3.8
  script:
    - echo "Running custom Python Security tests"
    - echo "Passed custom Python Security tests"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # This runs on the main branch
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'  # This runs on branches starting with 'feature/'
      when: always
    - when: never # Aviod running in other branches

dockerhub-amd64:
  stage: release-imgages
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_REGISTRY: "docker.io"
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_IMAGE_NAME: "$DOCKER_USERNAME/stock-flask-app"
    DOCKER_BASE_TAG: "latest"
    DOCKER_FILE: "Dockerfile"
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" $DOCKER_REGISTRY --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  script:
    - >
      docker buildx build
      --platform linux/amd64
      -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_BASE_TAG
      -f $DOCKER_FILE
      --push .
  only:
    - main
  needs:
    - job: dast
      optional: false

dockerhub-arm64:
  stage: release-imgages
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_REGISTRY: "docker.io"
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_IMAGE_NAME: "$DOCKER_USERNAME/stock-flask-app"
    DOCKER_BASE_TAG: "latest-arm64"
    DOCKER_FILE: "Dockerfile"
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" $DOCKER_REGISTRY --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  script:
    - >
      docker buildx build
      --platform linux/arm64
      -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_BASE_TAG
      -f $DOCKER_FILE
      --push .
  only:
    - main
  needs:
    - job: dast
      optional: false

test:
  stage: test
  rules:
    - when: never
