# Override the Auto DevOps 'test' stage
test:
  stage: test
  image: python:3.8
  script:
    - set -e  # Exit immediately if a command exits with a non-zero status.
    - pip3 install -r requirements.txt  # Install project dependencies.
    - python3 src/app.py &> /dev/null &  # Start the app in the background, suppress output.
    - sleep 5  # Wait for the Flask app to be up and running.
    - |
      response=$(curl --fail -s "http://localhost:5000/stock-price?symbol=AAPL")
      echo "Response: $response"
      if ! echo "$response" | grep -q '"symbol": "AAPL"'; then
        echo "Test failed: AAPL stock price not found in response."
        exit 1
      fi
    - kill $!  # Terminate the Flask app.
  only:
    - main  # Specify branches where this job should run, adjust as needed.

# Preserve Auto DevOps functionality
.auto_devops: &auto_devops
  before_script:
    - echo "Preserving Auto DevOps configurations"

# Example of another custom job (optional)
# This is just an example. You can define other custom jobs as needed.
custom_job_example:
  <<: *auto_devops
  stage: build
  script:
    - echo "This is a custom job example. Adjust or remove as necessary."
  only:
    - branches
