
include:
  - template: Auto-DevOps.gitlab-ci.yml

stages:
  - test

test:  # The herokuish buildpacks doesnt support Python Testing
  stage: test
  image: python:3.8
  script:
    - echo "Running custom tests instead of Auto DevOps tests"
    - pip install -r requirements.txt
    - pytest  tests/test-app.py
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
