
include:
  - template: Auto-DevOps.gitlab-ci.yml

stages:
  - test

test-override:  # The herokuish buildpacks doesnt support Python Testing
  stage: test
  image: python:3.8
  script:
    - echo "Running custom tests instead of Auto DevOps tests"
    - pip install -r requirements.txt
    - pytest  tests/test-app.py
  only:
    - main
