apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-flask-app-deployment
  labels:
    app: stock-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-flask-app
  template:
    metadata:
      labels:
        app: stock-flask-app
    spec:
      containers:
      - name: stock-flask-app
        image: bbertka/stock-flask-app:latest-arm64
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: stock-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
